-- Generated by the local-to-target delta scanner.
-- Additive only: target-only rows and destructive schema changes are excluded.

INSERT INTO schema_migrations (migration_name, migration_scope, checksum_sha256, execution_ms) VALUES ('131_review_rich_content_html.sql', 'schema', 'a2037a90c35927fc08fed3c5ad3b0d3c6ab17d22e587de454515c65ebc6755bc', 0) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO schema_migrations (migration_name, migration_scope, checksum_sha256, execution_ms) VALUES ('132_analytics_events.sql', 'schema', 'e43b0c8927690168e0a0c28ad538983e7e834e60d18e08a6bdaf7cf302106a68', 0) ON CONFLICT (migration_name) DO NOTHING;
