-- Generated by the local-to-target delta scanner.
-- Additive only: target-only rows and destructive schema changes are excluded.

CREATE SEQUENCE IF NOT EXISTS public."open_api_tokens_id_seq";

CREATE TABLE IF NOT EXISTS "open_api_tokens" (
    "id" bigint DEFAULT nextval('open_api_tokens_id_seq'::regclass) NOT NULL,
    "token_id" text NOT NULL,
    "tenant_slug" text NOT NULL,
    "token_name" text NOT NULL,
    "token_prefix" text NOT NULL,
    "token_digest" text NOT NULL,
    "token_ciphertext" text NOT NULL,
    "scopes_json" jsonb DEFAULT '["insight.publish"]'::jsonb NOT NULL,
    "status" text DEFAULT 'active'::text NOT NULL,
    "created_by_username" text DEFAULT ''::text NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "last_used_at" timestamp with time zone,
    "revoked_at" timestamp with time zone,
    "usage_count" bigint DEFAULT 0 NOT NULL
);

ALTER SEQUENCE public."open_api_tokens_id_seq" OWNED BY "open_api_tokens"."id";

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'open_api_tokens_pkey' AND conrelid = 'public.open_api_tokens'::regclass) THEN ALTER TABLE "open_api_tokens" ADD CONSTRAINT "open_api_tokens_pkey" PRIMARY KEY (id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'open_api_tokens_token_digest_key' AND conrelid = 'public.open_api_tokens'::regclass) THEN ALTER TABLE "open_api_tokens" ADD CONSTRAINT "open_api_tokens_token_digest_key" UNIQUE (token_digest); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'open_api_tokens_token_id_key' AND conrelid = 'public.open_api_tokens'::regclass) THEN ALTER TABLE "open_api_tokens" ADD CONSTRAINT "open_api_tokens_token_id_key" UNIQUE (token_id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'open_api_tokens_status_check' AND conrelid = 'public.open_api_tokens'::regclass) THEN ALTER TABLE "open_api_tokens" ADD CONSTRAINT "open_api_tokens_status_check" CHECK (status = ANY (ARRAY['active'::text, 'revoked'::text])); END IF; END $$;

CREATE INDEX IF NOT EXISTS idx_open_api_tokens_digest ON public.open_api_tokens USING btree (token_digest);

CREATE INDEX IF NOT EXISTS idx_open_api_tokens_tenant_status ON public.open_api_tokens USING btree (tenant_slug, status, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS open_api_tokens_pkey ON public.open_api_tokens USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS open_api_tokens_token_digest_key ON public.open_api_tokens USING btree (token_digest);

CREATE UNIQUE INDEX IF NOT EXISTS open_api_tokens_token_id_key ON public.open_api_tokens USING btree (token_id);

INSERT INTO schema_migrations (migration_name, migration_scope, checksum_sha256, execution_ms) VALUES ('133_repair_market_snapshot_schedule.sql', 'schema', '1c3b75798faefda035ce7f63f987904286035c0a1b55829b01cbc43fdabc8b63', 0) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO schema_migrations (migration_name, migration_scope, checksum_sha256, execution_ms) VALUES ('134_hourly_shared_market_and_news_sync.sql', 'schema', '1d9c78a43bc8d1616a326bea51bc54bfdb8126cca14235a412ab62a44bcf2ac1', 0) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO schema_migrations (migration_name, migration_scope, checksum_sha256, execution_ms) VALUES ('135_use_gangtise_market_snapshots.sql', 'schema', '7e980a65d704d89ebec70982887cc660c82d967e3cee7bff1424e9a8866e6027', 0) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO schema_migrations (migration_name, migration_scope, checksum_sha256, execution_ms) VALUES ('137_open_api_insight_tokens.sql', 'schema', 'e0554feeeeea1d70076fc58a70283525d7952e91902b0270fc19101324e2e6b1', 0) ON CONFLICT (migration_name) DO NOTHING;
