-- Generated by the local-to-target delta scanner.
-- Additive only: target-only rows and destructive schema changes are excluded.

CREATE TABLE IF NOT EXISTS "user_watchlist_items" (
    "id" bigint DEFAULT nextval('user_watchlist_items_id_seq'::regclass) NOT NULL,
    "tenant_slug" text DEFAULT ''::text NOT NULL,
    "user_profile_id" text DEFAULT ''::text NOT NULL,
    "stock_code" text DEFAULT ''::text NOT NULL,
    "stock_name" text DEFAULT ''::text NOT NULL,
    "market" text DEFAULT ''::text NOT NULL,
    "industry" text DEFAULT ''::text NOT NULL,
    "created_at" text NOT NULL,
    "updated_at" text NOT NULL
);

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_watchlist_items_pkey') THEN ALTER TABLE "user_watchlist_items" ADD CONSTRAINT "user_watchlist_items_pkey" PRIMARY KEY (id); END IF; END $$;

CREATE INDEX IF NOT EXISTS idx_user_watchlist_items_owner_updated ON public.user_watchlist_items USING btree (tenant_slug, user_profile_id, updated_at DESC, id DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uq_user_watchlist_items_owner_stock ON public.user_watchlist_items USING btree (tenant_slug, user_profile_id, stock_code);

CREATE UNIQUE INDEX IF NOT EXISTS user_watchlist_items_pkey ON public.user_watchlist_items USING btree (id);
