-- Generated by the local-to-target delta scanner.
-- Additive only: target-only rows and destructive schema changes are excluded.

ALTER TABLE "tenant_published_insights" ADD COLUMN IF NOT EXISTS "is_pinned" boolean DEFAULT false NOT NULL;

ALTER TABLE "tenant_published_insights" ADD COLUMN IF NOT EXISTS "pinned_at" timestamp with time zone;

CREATE INDEX IF NOT EXISTS idx_tenant_published_insights_editorial_feed ON public.tenant_published_insights USING btree (tenant_slug, is_pinned DESC, pinned_at DESC, published_date DESC, published_at DESC, imported_at DESC, id DESC);
