-- Generated by the local-to-target delta scanner.
-- Additive only: target-only rows and destructive schema changes are excluded.

CREATE SEQUENCE IF NOT EXISTS public."analytics_events_id_seq";

CREATE TABLE IF NOT EXISTS "analytics_events" (
    "id" bigint DEFAULT nextval('analytics_events_id_seq'::regclass) NOT NULL,
    "event_name" text NOT NULL,
    "event_category" text DEFAULT 'interaction'::text NOT NULL,
    "feature_key" text NOT NULL,
    "surface" text DEFAULT 'unknown'::text NOT NULL,
    "tenant_slug" text DEFAULT ''::text NOT NULL,
    "user_id" text DEFAULT ''::text NOT NULL,
    "user_profile_id" text DEFAULT ''::text NOT NULL,
    "user_role" text DEFAULT ''::text NOT NULL,
    "session_id" text DEFAULT ''::text NOT NULL,
    "anonymous_id" text DEFAULT ''::text NOT NULL,
    "object_type" text DEFAULT ''::text NOT NULL,
    "object_id" text DEFAULT ''::text NOT NULL,
    "path" text DEFAULT ''::text NOT NULL,
    "referrer" text DEFAULT ''::text NOT NULL,
    "event_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "duration_ms" integer,
    "success" boolean,
    "error_code" text DEFAULT ''::text NOT NULL,
    "properties_json" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER SEQUENCE public."analytics_events_id_seq" OWNED BY "analytics_events"."id";

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'analytics_events_pkey' AND conrelid = 'public.analytics_events'::regclass) THEN ALTER TABLE "analytics_events" ADD CONSTRAINT "analytics_events_pkey" PRIMARY KEY (id); END IF; END $$;

CREATE UNIQUE INDEX IF NOT EXISTS analytics_events_pkey ON public.analytics_events USING btree (id);

CREATE INDEX IF NOT EXISTS idx_analytics_events_event_at ON public.analytics_events USING btree (event_at DESC);

CREATE INDEX IF NOT EXISTS idx_analytics_events_feature_time ON public.analytics_events USING btree (feature_key, event_at DESC);

CREATE INDEX IF NOT EXISTS idx_analytics_events_profile_time ON public.analytics_events USING btree (user_profile_id, event_at DESC);

CREATE INDEX IF NOT EXISTS idx_analytics_events_session_time ON public.analytics_events USING btree (session_id, event_at, id);

CREATE INDEX IF NOT EXISTS idx_analytics_events_surface_time ON public.analytics_events USING btree (surface, event_at DESC);

CREATE INDEX IF NOT EXISTS idx_analytics_events_tenant_time ON public.analytics_events USING btree (tenant_slug, event_at DESC);

ALTER TABLE "tenant_insight_drafts" ADD COLUMN IF NOT EXISTS "content_html" text DEFAULT ''::text NOT NULL;
