-- Generated by the local-to-target delta scanner.
-- Additive only: target-only rows and destructive schema changes are excluded.

CREATE SEQUENCE IF NOT EXISTS public."tenant_broadcast_deliveries_id_seq";

CREATE TABLE IF NOT EXISTS "tenant_broadcast_deliveries" (
    "id" bigint DEFAULT nextval('tenant_broadcast_deliveries_id_seq'::regclass) NOT NULL,
    "tenant_slug" text NOT NULL,
    "broadcast_id" text NOT NULL,
    "user_profile_id" text NOT NULL,
    "thread_id" text DEFAULT ''::text NOT NULL,
    "delivery_status" text DEFAULT 'delivered'::text NOT NULL,
    "delivered_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "user_id" bigint
);

ALTER SEQUENCE public."tenant_broadcast_deliveries_id_seq" OWNED BY "tenant_broadcast_deliveries"."id";

CREATE SEQUENCE IF NOT EXISTS public."tenant_broadcasts_id_seq";

CREATE TABLE IF NOT EXISTS "tenant_broadcasts" (
    "id" bigint DEFAULT nextval('tenant_broadcasts_id_seq'::regclass) NOT NULL,
    "tenant_slug" text NOT NULL,
    "broadcast_id" text NOT NULL,
    "content" text DEFAULT ''::text NOT NULL,
    "broadcast_time" text DEFAULT ''::text NOT NULL,
    "reach" integer DEFAULT 0 NOT NULL,
    "open_rate" integer DEFAULT 0 NOT NULL,
    "target" text DEFAULT 'all'::text NOT NULL,
    "broadcast_type" text DEFAULT 'broadcast'::text NOT NULL,
    "broadcast_kind" text DEFAULT ''::text NOT NULL,
    "visual_theme" text DEFAULT ''::text NOT NULL,
    "insight_id" text DEFAULT ''::text NOT NULL,
    "is_simulated" boolean DEFAULT false NOT NULL,
    "simulation_label" text DEFAULT ''::text NOT NULL,
    "metadata_json" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER SEQUENCE public."tenant_broadcasts_id_seq" OWNED BY "tenant_broadcasts"."id";

CREATE SEQUENCE IF NOT EXISTS public."tenant_knowledge_documents_id_seq";

CREATE TABLE IF NOT EXISTS "tenant_knowledge_documents" (
    "id" bigint DEFAULT nextval('tenant_knowledge_documents_id_seq'::regclass) NOT NULL,
    "tenant_slug" text NOT NULL,
    "document_id" text NOT NULL,
    "document_type" text DEFAULT 'manual'::text NOT NULL,
    "title" text DEFAULT ''::text NOT NULL,
    "summary" text DEFAULT ''::text NOT NULL,
    "content_text" text DEFAULT ''::text NOT NULL,
    "content_html" text DEFAULT ''::text NOT NULL,
    "source" text DEFAULT ''::text NOT NULL,
    "source_detail" text DEFAULT ''::text NOT NULL,
    "status" text DEFAULT ''::text NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "document_json" jsonb DEFAULT '{}'::jsonb NOT NULL
);

ALTER SEQUENCE public."tenant_knowledge_documents_id_seq" OWNED BY "tenant_knowledge_documents"."id";

CREATE SEQUENCE IF NOT EXISTS public."tenant_message_threads_id_seq";

CREATE TABLE IF NOT EXISTS "tenant_message_threads" (
    "id" bigint DEFAULT nextval('tenant_message_threads_id_seq'::regclass) NOT NULL,
    "tenant_slug" text NOT NULL,
    "thread_id" text NOT NULL,
    "thread_type" text DEFAULT 'fan_interaction'::text NOT NULL,
    "name" text DEFAULT ''::text NOT NULL,
    "user_profile_id" text DEFAULT ''::text NOT NULL,
    "user_name" text DEFAULT ''::text NOT NULL,
    "user_avatar" text DEFAULT ''::text NOT NULL,
    "tier" text DEFAULT '粉丝'::text NOT NULL,
    "status" text DEFAULT '待处理'::text NOT NULL,
    "last_msg" text DEFAULT ''::text NOT NULL,
    "kol_unread" integer DEFAULT 0 NOT NULL,
    "user_unread" integer DEFAULT 0 NOT NULL,
    "last_sender" text DEFAULT ''::text NOT NULL,
    "last_message_type" text DEFAULT 'text'::text NOT NULL,
    "vip_only" boolean DEFAULT false NOT NULL,
    "is_simulated" boolean DEFAULT false NOT NULL,
    "simulation_label" text DEFAULT ''::text NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "metadata_json" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "user_id" bigint
);

ALTER SEQUENCE public."tenant_message_threads_id_seq" OWNED BY "tenant_message_threads"."id";

CREATE SEQUENCE IF NOT EXISTS public."tenant_messages_id_seq";

CREATE TABLE IF NOT EXISTS "tenant_messages" (
    "id" bigint DEFAULT nextval('tenant_messages_id_seq'::regclass) NOT NULL,
    "tenant_slug" text NOT NULL,
    "thread_id" text NOT NULL,
    "message_key" text NOT NULL,
    "sender" text DEFAULT 'user'::text NOT NULL,
    "content" text DEFAULT ''::text NOT NULL,
    "message_time" text DEFAULT ''::text NOT NULL,
    "message_type" text DEFAULT 'text'::text NOT NULL,
    "broadcast_kind" text DEFAULT ''::text NOT NULL,
    "visual_theme" text DEFAULT ''::text NOT NULL,
    "insight_id" text DEFAULT ''::text NOT NULL,
    "price" integer DEFAULT 0 NOT NULL,
    "preview" text DEFAULT ''::text NOT NULL,
    "metadata_json" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER SEQUENCE public."tenant_messages_id_seq" OWNED BY "tenant_messages"."id";

CREATE SEQUENCE IF NOT EXISTS public."tenant_published_insights_id_seq";

CREATE TABLE IF NOT EXISTS "tenant_published_insights" (
    "id" bigint DEFAULT nextval('tenant_published_insights_id_seq'::regclass) NOT NULL,
    "tenant_slug" text NOT NULL,
    "insight_id" text NOT NULL,
    "dav_id" text DEFAULT ''::text NOT NULL,
    "external_id" text DEFAULT ''::text NOT NULL,
    "title" text NOT NULL,
    "content_text" text NOT NULL,
    "content_html" text DEFAULT ''::text NOT NULL,
    "access_mode" text DEFAULT 'public'::text NOT NULL,
    "source_mode" text DEFAULT 'manual'::text NOT NULL,
    "published_date" date NOT NULL,
    "published_at" text DEFAULT ''::text NOT NULL,
    "imported_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "view_count" bigint DEFAULT 0 NOT NULL,
    "payload_json" jsonb DEFAULT '{}'::jsonb NOT NULL
);

ALTER SEQUENCE public."tenant_published_insights_id_seq" OWNED BY "tenant_published_insights"."id";

ALTER TABLE "app_settings" ADD COLUMN IF NOT EXISTS "revision" bigint DEFAULT 1 NOT NULL;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_broadcast_deliveries_pkey' AND conrelid = 'public.tenant_broadcast_deliveries'::regclass) THEN ALTER TABLE "tenant_broadcast_deliveries" ADD CONSTRAINT "tenant_broadcast_deliveries_pkey" PRIMARY KEY (id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_broadcast_deliveries_tenant_slug_broadcast_id_user_p_key' AND conrelid = 'public.tenant_broadcast_deliveries'::regclass) THEN ALTER TABLE "tenant_broadcast_deliveries" ADD CONSTRAINT "tenant_broadcast_deliveries_tenant_slug_broadcast_id_user_p_key" UNIQUE (tenant_slug, broadcast_id, user_profile_id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_broadcasts_pkey' AND conrelid = 'public.tenant_broadcasts'::regclass) THEN ALTER TABLE "tenant_broadcasts" ADD CONSTRAINT "tenant_broadcasts_pkey" PRIMARY KEY (id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_broadcasts_tenant_slug_broadcast_id_key' AND conrelid = 'public.tenant_broadcasts'::regclass) THEN ALTER TABLE "tenant_broadcasts" ADD CONSTRAINT "tenant_broadcasts_tenant_slug_broadcast_id_key" UNIQUE (tenant_slug, broadcast_id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_knowledge_documents_pkey' AND conrelid = 'public.tenant_knowledge_documents'::regclass) THEN ALTER TABLE "tenant_knowledge_documents" ADD CONSTRAINT "tenant_knowledge_documents_pkey" PRIMARY KEY (id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_knowledge_documents_tenant_slug_document_id_key' AND conrelid = 'public.tenant_knowledge_documents'::regclass) THEN ALTER TABLE "tenant_knowledge_documents" ADD CONSTRAINT "tenant_knowledge_documents_tenant_slug_document_id_key" UNIQUE (tenant_slug, document_id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_message_threads_pkey' AND conrelid = 'public.tenant_message_threads'::regclass) THEN ALTER TABLE "tenant_message_threads" ADD CONSTRAINT "tenant_message_threads_pkey" PRIMARY KEY (id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_message_threads_tenant_slug_thread_id_key' AND conrelid = 'public.tenant_message_threads'::regclass) THEN ALTER TABLE "tenant_message_threads" ADD CONSTRAINT "tenant_message_threads_tenant_slug_thread_id_key" UNIQUE (tenant_slug, thread_id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_messages_pkey' AND conrelid = 'public.tenant_messages'::regclass) THEN ALTER TABLE "tenant_messages" ADD CONSTRAINT "tenant_messages_pkey" PRIMARY KEY (id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_messages_tenant_slug_thread_id_message_key_key' AND conrelid = 'public.tenant_messages'::regclass) THEN ALTER TABLE "tenant_messages" ADD CONSTRAINT "tenant_messages_tenant_slug_thread_id_message_key_key" UNIQUE (tenant_slug, thread_id, message_key); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_published_insights_pkey' AND conrelid = 'public.tenant_published_insights'::regclass) THEN ALTER TABLE "tenant_published_insights" ADD CONSTRAINT "tenant_published_insights_pkey" PRIMARY KEY (id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_published_insights_tenant_slug_insight_id_key' AND conrelid = 'public.tenant_published_insights'::regclass) THEN ALTER TABLE "tenant_published_insights" ADD CONSTRAINT "tenant_published_insights_tenant_slug_insight_id_key" UNIQUE (tenant_slug, insight_id); END IF; END $$;

DO $$ BEGIN IF EXISTS (SELECT 1 FROM "tenant_broadcasts" WHERE tenant_slug IS NULL OR btrim(tenant_slug) = '' OR tenant_slug <> lower(btrim(tenant_slug))) THEN RAISE EXCEPTION 'tenant_registry_reference_invalid:tenant_broadcasts'; END IF; INSERT INTO tenant_registry (tenant_slug, tenant_name, created_at, updated_at) SELECT DISTINCT child.tenant_slug, child.tenant_slug, CURRENT_TIMESTAMP::text, CURRENT_TIMESTAMP::text FROM "tenant_broadcasts" child LEFT JOIN tenant_registry registry ON registry.tenant_slug = child.tenant_slug WHERE registry.tenant_slug IS NULL ON CONFLICT (tenant_slug) DO NOTHING; END $$;

DO $$ BEGIN IF EXISTS (SELECT 1 FROM "tenant_knowledge_documents" WHERE tenant_slug IS NULL OR btrim(tenant_slug) = '' OR tenant_slug <> lower(btrim(tenant_slug))) THEN RAISE EXCEPTION 'tenant_registry_reference_invalid:tenant_knowledge_documents'; END IF; INSERT INTO tenant_registry (tenant_slug, tenant_name, created_at, updated_at) SELECT DISTINCT child.tenant_slug, child.tenant_slug, CURRENT_TIMESTAMP::text, CURRENT_TIMESTAMP::text FROM "tenant_knowledge_documents" child LEFT JOIN tenant_registry registry ON registry.tenant_slug = child.tenant_slug WHERE registry.tenant_slug IS NULL ON CONFLICT (tenant_slug) DO NOTHING; END $$;

DO $$ BEGIN IF EXISTS (SELECT 1 FROM "tenant_message_threads" WHERE tenant_slug IS NULL OR btrim(tenant_slug) = '' OR tenant_slug <> lower(btrim(tenant_slug))) THEN RAISE EXCEPTION 'tenant_registry_reference_invalid:tenant_message_threads'; END IF; INSERT INTO tenant_registry (tenant_slug, tenant_name, created_at, updated_at) SELECT DISTINCT child.tenant_slug, child.tenant_slug, CURRENT_TIMESTAMP::text, CURRENT_TIMESTAMP::text FROM "tenant_message_threads" child LEFT JOIN tenant_registry registry ON registry.tenant_slug = child.tenant_slug WHERE registry.tenant_slug IS NULL ON CONFLICT (tenant_slug) DO NOTHING; END $$;

DO $$ BEGIN IF EXISTS (SELECT 1 FROM "tenant_published_insights" WHERE tenant_slug IS NULL OR btrim(tenant_slug) = '' OR tenant_slug <> lower(btrim(tenant_slug))) THEN RAISE EXCEPTION 'tenant_registry_reference_invalid:tenant_published_insights'; END IF; INSERT INTO tenant_registry (tenant_slug, tenant_name, created_at, updated_at) SELECT DISTINCT child.tenant_slug, child.tenant_slug, CURRENT_TIMESTAMP::text, CURRENT_TIMESTAMP::text FROM "tenant_published_insights" child LEFT JOIN tenant_registry registry ON registry.tenant_slug = child.tenant_slug WHERE registry.tenant_slug IS NULL ON CONFLICT (tenant_slug) DO NOTHING; END $$;

DO $$ BEGIN IF EXISTS (SELECT 1 FROM "open_api_tokens" WHERE tenant_slug IS NULL OR btrim(tenant_slug) = '' OR tenant_slug <> lower(btrim(tenant_slug))) THEN RAISE EXCEPTION 'tenant_registry_reference_invalid:open_api_tokens'; END IF; INSERT INTO tenant_registry (tenant_slug, tenant_name, created_at, updated_at) SELECT DISTINCT child.tenant_slug, child.tenant_slug, CURRENT_TIMESTAMP::text, CURRENT_TIMESTAMP::text FROM "open_api_tokens" child LEFT JOIN tenant_registry registry ON registry.tenant_slug = child.tenant_slug WHERE registry.tenant_slug IS NULL ON CONFLICT (tenant_slug) DO NOTHING; END $$;

DO $$ BEGIN IF EXISTS (SELECT 1 FROM "tenant_insight_drafts" WHERE tenant_slug IS NULL OR btrim(tenant_slug) = '' OR tenant_slug <> lower(btrim(tenant_slug))) THEN RAISE EXCEPTION 'tenant_registry_reference_invalid:tenant_insight_drafts'; END IF; INSERT INTO tenant_registry (tenant_slug, tenant_name, created_at, updated_at) SELECT DISTINCT child.tenant_slug, child.tenant_slug, CURRENT_TIMESTAMP::text, CURRENT_TIMESTAMP::text FROM "tenant_insight_drafts" child LEFT JOIN tenant_registry registry ON registry.tenant_slug = child.tenant_slug WHERE registry.tenant_slug IS NULL ON CONFLICT (tenant_slug) DO NOTHING; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_broadcast_deliveries_broadcast' AND conrelid = 'public.tenant_broadcast_deliveries'::regclass) THEN ALTER TABLE "tenant_broadcast_deliveries" ADD CONSTRAINT "fk_broadcast_deliveries_broadcast" FOREIGN KEY (tenant_slug, broadcast_id) REFERENCES tenant_broadcasts(tenant_slug, broadcast_id) ON DELETE CASCADE; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_broadcast_deliveries_user' AND conrelid = 'public.tenant_broadcast_deliveries'::regclass) THEN ALTER TABLE "tenant_broadcast_deliveries" ADD CONSTRAINT "fk_broadcast_deliveries_user" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_broadcasts_tenant' AND conrelid = 'public.tenant_broadcasts'::regclass) THEN ALTER TABLE "tenant_broadcasts" ADD CONSTRAINT "fk_broadcasts_tenant" FOREIGN KEY (tenant_slug) REFERENCES tenant_registry(tenant_slug) ON DELETE RESTRICT; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_knowledge_documents_tenant' AND conrelid = 'public.tenant_knowledge_documents'::regclass) THEN ALTER TABLE "tenant_knowledge_documents" ADD CONSTRAINT "fk_knowledge_documents_tenant" FOREIGN KEY (tenant_slug) REFERENCES tenant_registry(tenant_slug) ON DELETE RESTRICT; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_message_threads_tenant' AND conrelid = 'public.tenant_message_threads'::regclass) THEN ALTER TABLE "tenant_message_threads" ADD CONSTRAINT "fk_message_threads_tenant" FOREIGN KEY (tenant_slug) REFERENCES tenant_registry(tenant_slug) ON DELETE RESTRICT; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_message_threads_user' AND conrelid = 'public.tenant_message_threads'::regclass) THEN ALTER TABLE "tenant_message_threads" ADD CONSTRAINT "fk_message_threads_user" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_messages_thread' AND conrelid = 'public.tenant_messages'::regclass) THEN ALTER TABLE "tenant_messages" ADD CONSTRAINT "fk_messages_thread" FOREIGN KEY (tenant_slug, thread_id) REFERENCES tenant_message_threads(tenant_slug, thread_id) ON DELETE CASCADE; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_published_insights_tenant' AND conrelid = 'public.tenant_published_insights'::regclass) THEN ALTER TABLE "tenant_published_insights" ADD CONSTRAINT "fk_published_insights_tenant" FOREIGN KEY (tenant_slug) REFERENCES tenant_registry(tenant_slug) ON DELETE RESTRICT; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_open_api_tokens_tenant' AND conrelid = 'public.open_api_tokens'::regclass) THEN ALTER TABLE "open_api_tokens" ADD CONSTRAINT "fk_open_api_tokens_tenant" FOREIGN KEY (tenant_slug) REFERENCES tenant_registry(tenant_slug) ON DELETE RESTRICT; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_insight_drafts_tenant' AND conrelid = 'public.tenant_insight_drafts'::regclass) THEN ALTER TABLE "tenant_insight_drafts" ADD CONSTRAINT "fk_insight_drafts_tenant" FOREIGN KEY (tenant_slug) REFERENCES tenant_registry(tenant_slug) ON DELETE RESTRICT; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_published_insights_access_mode_check' AND conrelid = 'public.tenant_published_insights'::regclass) THEN ALTER TABLE "tenant_published_insights" ADD CONSTRAINT "tenant_published_insights_access_mode_check" CHECK (access_mode = ANY (ARRAY['public'::text, 'subscriber'::text])); END IF; END $$;

CREATE INDEX IF NOT EXISTS idx_tenant_broadcast_deliveries_profile ON public.tenant_broadcast_deliveries USING btree (tenant_slug, user_profile_id, delivered_at DESC);

CREATE INDEX IF NOT EXISTS idx_tenant_broadcast_deliveries_user_id ON public.tenant_broadcast_deliveries USING btree (tenant_slug, user_id, delivered_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_broadcast_deliveries_pkey ON public.tenant_broadcast_deliveries USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_broadcast_deliveries_tenant_slug_broadcast_id_user_p_key ON public.tenant_broadcast_deliveries USING btree (tenant_slug, broadcast_id, user_profile_id);

CREATE INDEX IF NOT EXISTS idx_tenant_broadcasts_time ON public.tenant_broadcasts USING btree (tenant_slug, broadcast_time DESC, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_broadcasts_pkey ON public.tenant_broadcasts USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_broadcasts_tenant_slug_broadcast_id_key ON public.tenant_broadcasts USING btree (tenant_slug, broadcast_id);

CREATE INDEX IF NOT EXISTS idx_tenant_knowledge_documents_type ON public.tenant_knowledge_documents USING btree (tenant_slug, document_type, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_tenant_knowledge_documents_updated ON public.tenant_knowledge_documents USING btree (tenant_slug, updated_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_knowledge_documents_pkey ON public.tenant_knowledge_documents USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_knowledge_documents_tenant_slug_document_id_key ON public.tenant_knowledge_documents USING btree (tenant_slug, document_id);

CREATE INDEX IF NOT EXISTS idx_tenant_message_threads_updated ON public.tenant_message_threads USING btree (tenant_slug, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_tenant_message_threads_user_id ON public.tenant_message_threads USING btree (tenant_slug, user_id, updated_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_message_threads_pkey ON public.tenant_message_threads USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_message_threads_tenant_slug_thread_id_key ON public.tenant_message_threads USING btree (tenant_slug, thread_id);

CREATE INDEX IF NOT EXISTS idx_tenant_messages_thread_time ON public.tenant_messages USING btree (tenant_slug, thread_id, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_messages_pkey ON public.tenant_messages USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_messages_tenant_slug_thread_id_message_key_key ON public.tenant_messages USING btree (tenant_slug, thread_id, message_key);

CREATE INDEX IF NOT EXISTS idx_tenant_published_insights_feed ON public.tenant_published_insights USING btree (tenant_slug, published_date DESC, published_at DESC, imported_at DESC, id DESC);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_published_insights_pkey ON public.tenant_published_insights USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_published_insights_tenant_slug_insight_id_key ON public.tenant_published_insights USING btree (tenant_slug, insight_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tenant_published_insights_external_id ON public.tenant_published_insights USING btree (tenant_slug, external_id) WHERE (external_id <> ''::text);

CREATE INDEX IF NOT EXISTS idx_open_api_tokens_tenant_id ON public.open_api_tokens USING btree (tenant_slug, token_id);

CREATE INDEX IF NOT EXISTS idx_tenant_insight_drafts_tenant_id ON public.tenant_insight_drafts USING btree (tenant_slug, draft_id);

INSERT INTO schema_migrations (migration_name, migration_scope, checksum_sha256, execution_ms) VALUES ('138_tenant_published_insights.sql', 'schema', 'e5733f1a4d3910b0f6c7ec6f622eea691a12352c1d74ca78a1a451973d3db353', 0) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO schema_migrations (migration_name, migration_scope, checksum_sha256, execution_ms) VALUES ('139_message_center_domain.sql', 'schema', '909659570e6805f4b17ec06021dc38326a06c6062eb50344c86ce53739b65873', 0) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO schema_migrations (migration_name, migration_scope, checksum_sha256, execution_ms) VALUES ('140_knowledge_domain.sql', 'schema', '38ef6241403abded1174c837e1b3393a873646c7b359b6559010cb6e1b580cf6', 0) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO schema_migrations (migration_name, migration_scope, checksum_sha256, execution_ms) VALUES ('141_app_settings_revision.sql', 'schema', '31c67ea36cf730de72795538d9e577ab4631ec883a12441d94f52e0491f6473f', 0) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO schema_migrations (migration_name, migration_scope, checksum_sha256, execution_ms) VALUES ('142_domain_foreign_keys.sql', 'schema', '24a0dd9e11427f3b1c0254fbbf58866933c6f5ed7914bc0f248974ec930a7888', 0) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO schema_migrations (migration_name, migration_scope, checksum_sha256, execution_ms) VALUES ('143_domain_tenant_ownership.sql', 'schema', '0e68178a4d7ad2b8a2c9f7edfbf991e00c52d1da0b3bb14c61b2f231d2318978', 0) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO schema_migrations (migration_name, migration_scope, checksum_sha256, execution_ms) VALUES ('144_message_domain_user_identity.sql', 'schema', 'a0a6ccd1613470100d0036c1a6187235ef48613d73069db69d718194a93d78fd', 0) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO schema_migrations (migration_name, migration_scope, checksum_sha256, execution_ms) VALUES ('145_reconcile_tenant_registry_references.sql', 'schema', '0eb6e53a4e4d93f24f69fd6a083bafe6bb63a44102145224fbf22a5fb81811c7', 0) ON CONFLICT (migration_name) DO NOTHING;
