-- Generated by the local-to-target delta scanner.
-- Additive only: target-only rows and destructive schema changes are excluded.

CREATE SEQUENCE IF NOT EXISTS public."analytics_events_id_seq";

CREATE TABLE IF NOT EXISTS "analytics_events" (
    "id" bigint DEFAULT nextval('analytics_events_id_seq'::regclass) NOT NULL,
    "event_name" text NOT NULL,
    "event_category" text DEFAULT 'interaction'::text NOT NULL,
    "feature_key" text NOT NULL,
    "surface" text DEFAULT 'unknown'::text NOT NULL,
    "tenant_slug" text DEFAULT ''::text NOT NULL,
    "user_id" text DEFAULT ''::text NOT NULL,
    "user_profile_id" text DEFAULT ''::text NOT NULL,
    "user_role" text DEFAULT ''::text NOT NULL,
    "session_id" text DEFAULT ''::text NOT NULL,
    "anonymous_id" text DEFAULT ''::text NOT NULL,
    "object_type" text DEFAULT ''::text NOT NULL,
    "object_id" text DEFAULT ''::text NOT NULL,
    "path" text DEFAULT ''::text NOT NULL,
    "referrer" text DEFAULT ''::text NOT NULL,
    "event_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "duration_ms" integer,
    "success" boolean,
    "error_code" text DEFAULT ''::text NOT NULL,
    "properties_json" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER SEQUENCE public."analytics_events_id_seq" OWNED BY "analytics_events"."id";

CREATE SEQUENCE IF NOT EXISTS public."daily_quiz_sets_id_seq";

CREATE TABLE IF NOT EXISTS "daily_quiz_sets" (
    "id" bigint DEFAULT nextval('daily_quiz_sets_id_seq'::regclass) NOT NULL,
    "quiz_date" text NOT NULL,
    "question_id" bigint NOT NULL,
    "display_order" integer NOT NULL,
    "selection_seed" text DEFAULT ''::text NOT NULL,
    "created_at" text NOT NULL
);

ALTER SEQUENCE public."daily_quiz_sets_id_seq" OWNED BY "daily_quiz_sets"."id";

CREATE SEQUENCE IF NOT EXISTS public."fan_payment_orders_id_seq";

CREATE TABLE IF NOT EXISTS "fan_payment_orders" (
    "id" bigint DEFAULT nextval('fan_payment_orders_id_seq'::regclass) NOT NULL,
    "order_no" text NOT NULL,
    "tenant_slug" text NOT NULL,
    "user_id" bigint NOT NULL,
    "product_id" bigint NOT NULL,
    "amount_cents" integer NOT NULL,
    "currency" text DEFAULT 'CNY'::text NOT NULL,
    "payment_channel" text DEFAULT 'manual_transfer'::text NOT NULL,
    "status" text DEFAULT 'pending'::text NOT NULL,
    "provider_trade_no" text DEFAULT ''::text NOT NULL,
    "payment_reference" text DEFAULT ''::text NOT NULL,
    "metadata_json" text DEFAULT '{}'::text NOT NULL,
    "created_at" text NOT NULL,
    "expires_at" text NOT NULL,
    "paid_at" text DEFAULT ''::text NOT NULL,
    "confirmed_by_user_id" bigint,
    "confirmed_at" text DEFAULT ''::text NOT NULL,
    "updated_at" text NOT NULL
);

ALTER SEQUENCE public."fan_payment_orders_id_seq" OWNED BY "fan_payment_orders"."id";

CREATE SEQUENCE IF NOT EXISTS public."fan_subscriptions_id_seq";

CREATE TABLE IF NOT EXISTS "fan_subscriptions" (
    "id" bigint DEFAULT nextval('fan_subscriptions_id_seq'::regclass) NOT NULL,
    "tenant_slug" text NOT NULL,
    "user_id" bigint NOT NULL,
    "product_id" bigint NOT NULL,
    "order_id" bigint NOT NULL,
    "status" text DEFAULT 'active'::text NOT NULL,
    "starts_at" text NOT NULL,
    "expires_at" text NOT NULL,
    "created_at" text NOT NULL,
    "updated_at" text NOT NULL
);

ALTER SEQUENCE public."fan_subscriptions_id_seq" OWNED BY "fan_subscriptions"."id";

CREATE SEQUENCE IF NOT EXISTS public."quiz_questions_id_seq";

CREATE TABLE IF NOT EXISTS "quiz_questions" (
    "id" bigint DEFAULT nextval('quiz_questions_id_seq'::regclass) NOT NULL,
    "question_code" text NOT NULL,
    "question_text" text NOT NULL,
    "question_type" text DEFAULT 'single_choice'::text NOT NULL,
    "options_json" text DEFAULT '[]'::text NOT NULL,
    "correct_answer" text NOT NULL,
    "explanation" text DEFAULT ''::text NOT NULL,
    "category" text DEFAULT '基础知识'::text NOT NULL,
    "difficulty" text DEFAULT '基础'::text NOT NULL,
    "source" text DEFAULT 'curated_question_bank_v1'::text NOT NULL,
    "review_status" text DEFAULT 'approved'::text NOT NULL,
    "is_active" integer DEFAULT 1 NOT NULL,
    "created_at" text NOT NULL,
    "updated_at" text NOT NULL
);

ALTER SEQUENCE public."quiz_questions_id_seq" OWNED BY "quiz_questions"."id";

CREATE SEQUENCE IF NOT EXISTS public."tenant_fan_qr_invite_claims_id_seq";

CREATE TABLE IF NOT EXISTS "tenant_fan_qr_invite_claims" (
    "id" bigint DEFAULT nextval('tenant_fan_qr_invite_claims_id_seq'::regclass) NOT NULL,
    "invite_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "tenant_slug" text NOT NULL,
    "claimed_at" text NOT NULL
);

ALTER SEQUENCE public."tenant_fan_qr_invite_claims_id_seq" OWNED BY "tenant_fan_qr_invite_claims"."id";

CREATE SEQUENCE IF NOT EXISTS public."tenant_fan_qr_invites_id_seq";

CREATE TABLE IF NOT EXISTS "tenant_fan_qr_invites" (
    "id" bigint DEFAULT nextval('tenant_fan_qr_invites_id_seq'::regclass) NOT NULL,
    "invite_token" text NOT NULL,
    "tenant_slug" text NOT NULL,
    "source_label" text DEFAULT '扫码导入'::text NOT NULL,
    "note" text DEFAULT ''::text NOT NULL,
    "status" text DEFAULT 'active'::text NOT NULL,
    "max_uses" integer DEFAULT 0 NOT NULL,
    "used_count" integer DEFAULT 0 NOT NULL,
    "expires_at" text DEFAULT ''::text NOT NULL,
    "created_by_user_id" bigint,
    "created_at" text NOT NULL,
    "updated_at" text NOT NULL,
    "qr_image_data" text DEFAULT ''::text NOT NULL,
    "registration_type" text DEFAULT 'free'::text NOT NULL
);

ALTER SEQUENCE public."tenant_fan_qr_invites_id_seq" OWNED BY "tenant_fan_qr_invites"."id";

CREATE SEQUENCE IF NOT EXISTS public."tenant_insight_drafts_id_seq";

CREATE TABLE IF NOT EXISTS "tenant_insight_drafts" (
    "id" bigint DEFAULT nextval('tenant_insight_drafts_id_seq'::regclass) NOT NULL,
    "tenant_slug" text NOT NULL,
    "draft_id" text NOT NULL,
    "title" text DEFAULT ''::text NOT NULL,
    "content_text" text NOT NULL,
    "source_mode" text DEFAULT 'manual'::text NOT NULL,
    "access_mode" text DEFAULT 'public'::text NOT NULL,
    "created_at" text NOT NULL,
    "updated_at" text NOT NULL,
    "content_html" text DEFAULT ''::text NOT NULL
);

ALTER SEQUENCE public."tenant_insight_drafts_id_seq" OWNED BY "tenant_insight_drafts"."id";

CREATE TABLE IF NOT EXISTS "tenant_registry" (
    "tenant_slug" text NOT NULL,
    "tenant_name" text DEFAULT ''::text NOT NULL,
    "created_at" text NOT NULL,
    "updated_at" text NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS public."tenant_subscription_products_id_seq";

CREATE TABLE IF NOT EXISTS "tenant_subscription_products" (
    "id" bigint DEFAULT nextval('tenant_subscription_products_id_seq'::regclass) NOT NULL,
    "tenant_slug" text NOT NULL,
    "product_code" text NOT NULL,
    "name" text NOT NULL,
    "description" text DEFAULT ''::text NOT NULL,
    "price_cents" integer NOT NULL,
    "billing_period_days" integer NOT NULL,
    "status" text DEFAULT 'active'::text NOT NULL,
    "created_by_user_id" bigint,
    "created_at" text NOT NULL,
    "updated_at" text NOT NULL
);

ALTER SEQUENCE public."tenant_subscription_products_id_seq" OWNED BY "tenant_subscription_products"."id";

CREATE SEQUENCE IF NOT EXISTS public."user_quiz_answers_id_seq";

CREATE TABLE IF NOT EXISTS "user_quiz_answers" (
    "id" bigint DEFAULT nextval('user_quiz_answers_id_seq'::regclass) NOT NULL,
    "attempt_id" bigint NOT NULL,
    "question_id" bigint NOT NULL,
    "selected_answer" text DEFAULT ''::text NOT NULL,
    "correct_answer_snapshot" text NOT NULL,
    "is_correct" integer DEFAULT 0 NOT NULL,
    "answered_at" text NOT NULL
);

ALTER SEQUENCE public."user_quiz_answers_id_seq" OWNED BY "user_quiz_answers"."id";

CREATE SEQUENCE IF NOT EXISTS public."user_quiz_attempts_id_seq";

CREATE TABLE IF NOT EXISTS "user_quiz_attempts" (
    "id" bigint DEFAULT nextval('user_quiz_attempts_id_seq'::regclass) NOT NULL,
    "tenant_slug" text NOT NULL,
    "user_id" bigint NOT NULL,
    "quiz_date" text NOT NULL,
    "started_at" text NOT NULL,
    "completed_at" text DEFAULT ''::text NOT NULL,
    "score" integer DEFAULT 0 NOT NULL,
    "correct_count" integer DEFAULT 0 NOT NULL,
    "total_count" integer DEFAULT 5 NOT NULL,
    "duration_seconds" integer DEFAULT 0 NOT NULL,
    "attempt_no" integer DEFAULT 1 NOT NULL
);

ALTER SEQUENCE public."user_quiz_attempts_id_seq" OWNED BY "user_quiz_attempts"."id";

ALTER TABLE "fan_stock_observation_events" ADD COLUMN IF NOT EXISTS "user_id" bigint;

ALTER TABLE "user_watchlist_items" ADD COLUMN IF NOT EXISTS "user_id" bigint;

ALTER TABLE "watchlist_comments" ADD COLUMN IF NOT EXISTS "created_by_user_pk" bigint;

ALTER TABLE "watchlist_kline_annotations" ADD COLUMN IF NOT EXISTS "created_by_user_pk" bigint;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'analytics_events_pkey' AND conrelid = 'public.analytics_events'::regclass) THEN ALTER TABLE "analytics_events" ADD CONSTRAINT "analytics_events_pkey" PRIMARY KEY (id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'daily_quiz_sets_pkey' AND conrelid = 'public.daily_quiz_sets'::regclass) THEN ALTER TABLE "daily_quiz_sets" ADD CONSTRAINT "daily_quiz_sets_pkey" PRIMARY KEY (id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'daily_quiz_sets_quiz_date_display_order_key' AND conrelid = 'public.daily_quiz_sets'::regclass) THEN ALTER TABLE "daily_quiz_sets" ADD CONSTRAINT "daily_quiz_sets_quiz_date_display_order_key" UNIQUE (quiz_date, display_order); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'daily_quiz_sets_quiz_date_question_id_key' AND conrelid = 'public.daily_quiz_sets'::regclass) THEN ALTER TABLE "daily_quiz_sets" ADD CONSTRAINT "daily_quiz_sets_quiz_date_question_id_key" UNIQUE (quiz_date, question_id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fan_payment_orders_order_no_key' AND conrelid = 'public.fan_payment_orders'::regclass) THEN ALTER TABLE "fan_payment_orders" ADD CONSTRAINT "fan_payment_orders_order_no_key" UNIQUE (order_no); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fan_payment_orders_pkey' AND conrelid = 'public.fan_payment_orders'::regclass) THEN ALTER TABLE "fan_payment_orders" ADD CONSTRAINT "fan_payment_orders_pkey" PRIMARY KEY (id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fan_subscriptions_order_id_key' AND conrelid = 'public.fan_subscriptions'::regclass) THEN ALTER TABLE "fan_subscriptions" ADD CONSTRAINT "fan_subscriptions_order_id_key" UNIQUE (order_id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fan_subscriptions_pkey' AND conrelid = 'public.fan_subscriptions'::regclass) THEN ALTER TABLE "fan_subscriptions" ADD CONSTRAINT "fan_subscriptions_pkey" PRIMARY KEY (id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'quiz_questions_pkey' AND conrelid = 'public.quiz_questions'::regclass) THEN ALTER TABLE "quiz_questions" ADD CONSTRAINT "quiz_questions_pkey" PRIMARY KEY (id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'quiz_questions_question_code_key' AND conrelid = 'public.quiz_questions'::regclass) THEN ALTER TABLE "quiz_questions" ADD CONSTRAINT "quiz_questions_question_code_key" UNIQUE (question_code); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_fan_qr_invite_claims_invite_id_user_id_key' AND conrelid = 'public.tenant_fan_qr_invite_claims'::regclass) THEN ALTER TABLE "tenant_fan_qr_invite_claims" ADD CONSTRAINT "tenant_fan_qr_invite_claims_invite_id_user_id_key" UNIQUE (invite_id, user_id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_fan_qr_invite_claims_pkey' AND conrelid = 'public.tenant_fan_qr_invite_claims'::regclass) THEN ALTER TABLE "tenant_fan_qr_invite_claims" ADD CONSTRAINT "tenant_fan_qr_invite_claims_pkey" PRIMARY KEY (id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_fan_qr_invites_invite_token_key' AND conrelid = 'public.tenant_fan_qr_invites'::regclass) THEN ALTER TABLE "tenant_fan_qr_invites" ADD CONSTRAINT "tenant_fan_qr_invites_invite_token_key" UNIQUE (invite_token); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_fan_qr_invites_pkey' AND conrelid = 'public.tenant_fan_qr_invites'::regclass) THEN ALTER TABLE "tenant_fan_qr_invites" ADD CONSTRAINT "tenant_fan_qr_invites_pkey" PRIMARY KEY (id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_insight_drafts_pkey' AND conrelid = 'public.tenant_insight_drafts'::regclass) THEN ALTER TABLE "tenant_insight_drafts" ADD CONSTRAINT "tenant_insight_drafts_pkey" PRIMARY KEY (id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_insight_drafts_tenant_slug_draft_id_key' AND conrelid = 'public.tenant_insight_drafts'::regclass) THEN ALTER TABLE "tenant_insight_drafts" ADD CONSTRAINT "tenant_insight_drafts_tenant_slug_draft_id_key" UNIQUE (tenant_slug, draft_id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_registry_pkey' AND conrelid = 'public.tenant_registry'::regclass) THEN ALTER TABLE "tenant_registry" ADD CONSTRAINT "tenant_registry_pkey" PRIMARY KEY (tenant_slug); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_subscription_products_pkey' AND conrelid = 'public.tenant_subscription_products'::regclass) THEN ALTER TABLE "tenant_subscription_products" ADD CONSTRAINT "tenant_subscription_products_pkey" PRIMARY KEY (id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_subscription_products_tenant_slug_product_code_key' AND conrelid = 'public.tenant_subscription_products'::regclass) THEN ALTER TABLE "tenant_subscription_products" ADD CONSTRAINT "tenant_subscription_products_tenant_slug_product_code_key" UNIQUE (tenant_slug, product_code); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_quiz_answers_attempt_id_question_id_key' AND conrelid = 'public.user_quiz_answers'::regclass) THEN ALTER TABLE "user_quiz_answers" ADD CONSTRAINT "user_quiz_answers_attempt_id_question_id_key" UNIQUE (attempt_id, question_id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_quiz_answers_pkey' AND conrelid = 'public.user_quiz_answers'::regclass) THEN ALTER TABLE "user_quiz_answers" ADD CONSTRAINT "user_quiz_answers_pkey" PRIMARY KEY (id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_quiz_attempts_pkey' AND conrelid = 'public.user_quiz_attempts'::regclass) THEN ALTER TABLE "user_quiz_attempts" ADD CONSTRAINT "user_quiz_attempts_pkey" PRIMARY KEY (id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'daily_quiz_sets_question_id_fkey' AND conrelid = 'public.daily_quiz_sets'::regclass) THEN ALTER TABLE "daily_quiz_sets" ADD CONSTRAINT "daily_quiz_sets_question_id_fkey" FOREIGN KEY (question_id) REFERENCES quiz_questions(id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fan_payment_orders_product_id_fkey' AND conrelid = 'public.fan_payment_orders'::regclass) THEN ALTER TABLE "fan_payment_orders" ADD CONSTRAINT "fan_payment_orders_product_id_fkey" FOREIGN KEY (product_id) REFERENCES tenant_subscription_products(id) ON DELETE RESTRICT; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fan_payment_orders_user_id_fkey' AND conrelid = 'public.fan_payment_orders'::regclass) THEN ALTER TABLE "fan_payment_orders" ADD CONSTRAINT "fan_payment_orders_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fan_subscriptions_order_id_fkey' AND conrelid = 'public.fan_subscriptions'::regclass) THEN ALTER TABLE "fan_subscriptions" ADD CONSTRAINT "fan_subscriptions_order_id_fkey" FOREIGN KEY (order_id) REFERENCES fan_payment_orders(id) ON DELETE RESTRICT; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fan_subscriptions_product_id_fkey' AND conrelid = 'public.fan_subscriptions'::regclass) THEN ALTER TABLE "fan_subscriptions" ADD CONSTRAINT "fan_subscriptions_product_id_fkey" FOREIGN KEY (product_id) REFERENCES tenant_subscription_products(id) ON DELETE RESTRICT; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fan_subscriptions_user_id_fkey' AND conrelid = 'public.fan_subscriptions'::regclass) THEN ALTER TABLE "fan_subscriptions" ADD CONSTRAINT "fan_subscriptions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_fan_qr_invite_claims_invite_id_fkey' AND conrelid = 'public.tenant_fan_qr_invite_claims'::regclass) THEN ALTER TABLE "tenant_fan_qr_invite_claims" ADD CONSTRAINT "tenant_fan_qr_invite_claims_invite_id_fkey" FOREIGN KEY (invite_id) REFERENCES tenant_fan_qr_invites(id) ON DELETE CASCADE; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_fan_qr_invite_claims_user_id_fkey' AND conrelid = 'public.tenant_fan_qr_invite_claims'::regclass) THEN ALTER TABLE "tenant_fan_qr_invite_claims" ADD CONSTRAINT "tenant_fan_qr_invite_claims_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_quiz_answers_attempt_id_fkey' AND conrelid = 'public.user_quiz_answers'::regclass) THEN ALTER TABLE "user_quiz_answers" ADD CONSTRAINT "user_quiz_answers_attempt_id_fkey" FOREIGN KEY (attempt_id) REFERENCES user_quiz_attempts(id) ON DELETE CASCADE; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_quiz_answers_question_id_fkey' AND conrelid = 'public.user_quiz_answers'::regclass) THEN ALTER TABLE "user_quiz_answers" ADD CONSTRAINT "user_quiz_answers_question_id_fkey" FOREIGN KEY (question_id) REFERENCES quiz_questions(id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_quiz_attempts_user_id_fkey' AND conrelid = 'public.user_quiz_attempts'::regclass) THEN ALTER TABLE "user_quiz_attempts" ADD CONSTRAINT "user_quiz_attempts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_fan_stock_observation_user' AND conrelid = 'public.fan_stock_observation_events'::regclass) THEN ALTER TABLE "fan_stock_observation_events" ADD CONSTRAINT "fk_fan_stock_observation_user" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_watchlist_items_user' AND conrelid = 'public.user_watchlist_items'::regclass) THEN ALTER TABLE "user_watchlist_items" ADD CONSTRAINT "fk_user_watchlist_items_user" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_watchlist_comments_created_by_user' AND conrelid = 'public.watchlist_comments'::regclass) THEN ALTER TABLE "watchlist_comments" ADD CONSTRAINT "fk_watchlist_comments_created_by_user" FOREIGN KEY (created_by_user_pk) REFERENCES users(id) ON DELETE SET NULL; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_watchlist_annotations_created_by_user' AND conrelid = 'public.watchlist_kline_annotations'::regclass) THEN ALTER TABLE "watchlist_kline_annotations" ADD CONSTRAINT "fk_watchlist_annotations_created_by_user" FOREIGN KEY (created_by_user_pk) REFERENCES users(id) ON DELETE SET NULL; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fan_payment_orders_amount_cents_check' AND conrelid = 'public.fan_payment_orders'::regclass) THEN ALTER TABLE "fan_payment_orders" ADD CONSTRAINT "fan_payment_orders_amount_cents_check" CHECK (amount_cents >= 0); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fan_payment_orders_status_check' AND conrelid = 'public.fan_payment_orders'::regclass) THEN ALTER TABLE "fan_payment_orders" ADD CONSTRAINT "fan_payment_orders_status_check" CHECK (status = ANY (ARRAY['pending'::text, 'paid'::text, 'cancelled'::text, 'expired'::text, 'refunded'::text])); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fan_subscriptions_status_check' AND conrelid = 'public.fan_subscriptions'::regclass) THEN ALTER TABLE "fan_subscriptions" ADD CONSTRAINT "fan_subscriptions_status_check" CHECK (status = ANY (ARRAY['active'::text, 'expired'::text, 'cancelled'::text, 'refunded'::text])); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_fan_qr_invites_max_uses_check' AND conrelid = 'public.tenant_fan_qr_invites'::regclass) THEN ALTER TABLE "tenant_fan_qr_invites" ADD CONSTRAINT "tenant_fan_qr_invites_max_uses_check" CHECK (max_uses >= 0); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_fan_qr_invites_registration_type_check' AND conrelid = 'public.tenant_fan_qr_invites'::regclass) THEN ALTER TABLE "tenant_fan_qr_invites" ADD CONSTRAINT "tenant_fan_qr_invites_registration_type_check" CHECK (registration_type = ANY (ARRAY['free'::text, 'subscriber'::text])); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_fan_qr_invites_status_check' AND conrelid = 'public.tenant_fan_qr_invites'::regclass) THEN ALTER TABLE "tenant_fan_qr_invites" ADD CONSTRAINT "tenant_fan_qr_invites_status_check" CHECK (status = ANY (ARRAY['active'::text, 'disabled'::text, 'expired'::text])); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_fan_qr_invites_used_count_check' AND conrelid = 'public.tenant_fan_qr_invites'::regclass) THEN ALTER TABLE "tenant_fan_qr_invites" ADD CONSTRAINT "tenant_fan_qr_invites_used_count_check" CHECK (used_count >= 0); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_subscription_products_billing_period_days_check' AND conrelid = 'public.tenant_subscription_products'::regclass) THEN ALTER TABLE "tenant_subscription_products" ADD CONSTRAINT "tenant_subscription_products_billing_period_days_check" CHECK (billing_period_days > 0); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_subscription_products_price_cents_check' AND conrelid = 'public.tenant_subscription_products'::regclass) THEN ALTER TABLE "tenant_subscription_products" ADD CONSTRAINT "tenant_subscription_products_price_cents_check" CHECK (price_cents >= 0); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_subscription_products_status_check' AND conrelid = 'public.tenant_subscription_products'::regclass) THEN ALTER TABLE "tenant_subscription_products" ADD CONSTRAINT "tenant_subscription_products_status_check" CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'archived'::text])); END IF; END $$;

CREATE UNIQUE INDEX IF NOT EXISTS analytics_events_pkey ON public.analytics_events USING btree (id);

CREATE INDEX IF NOT EXISTS idx_analytics_events_event_at ON public.analytics_events USING btree (event_at DESC);

CREATE INDEX IF NOT EXISTS idx_analytics_events_feature_time ON public.analytics_events USING btree (feature_key, event_at DESC);

CREATE INDEX IF NOT EXISTS idx_analytics_events_profile_time ON public.analytics_events USING btree (user_profile_id, event_at DESC);

CREATE INDEX IF NOT EXISTS idx_analytics_events_session_time ON public.analytics_events USING btree (session_id, event_at, id);

CREATE INDEX IF NOT EXISTS idx_analytics_events_surface_time ON public.analytics_events USING btree (surface, event_at DESC);

CREATE INDEX IF NOT EXISTS idx_analytics_events_tenant_time ON public.analytics_events USING btree (tenant_slug, event_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS daily_quiz_sets_pkey ON public.daily_quiz_sets USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS daily_quiz_sets_quiz_date_display_order_key ON public.daily_quiz_sets USING btree (quiz_date, display_order);

CREATE UNIQUE INDEX IF NOT EXISTS daily_quiz_sets_quiz_date_question_id_key ON public.daily_quiz_sets USING btree (quiz_date, question_id);

CREATE INDEX IF NOT EXISTS idx_daily_quiz_sets_date ON public.daily_quiz_sets USING btree (quiz_date, display_order);

CREATE UNIQUE INDEX IF NOT EXISTS fan_payment_orders_order_no_key ON public.fan_payment_orders USING btree (order_no);

CREATE UNIQUE INDEX IF NOT EXISTS fan_payment_orders_pkey ON public.fan_payment_orders USING btree (id);

CREATE INDEX IF NOT EXISTS idx_fan_payment_orders_tenant_status ON public.fan_payment_orders USING btree (tenant_slug, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_fan_payment_orders_user_status ON public.fan_payment_orders USING btree (user_id, status, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS fan_subscriptions_order_id_key ON public.fan_subscriptions USING btree (order_id);

CREATE UNIQUE INDEX IF NOT EXISTS fan_subscriptions_pkey ON public.fan_subscriptions USING btree (id);

CREATE INDEX IF NOT EXISTS idx_fan_subscriptions_access ON public.fan_subscriptions USING btree (tenant_slug, user_id, status, expires_at DESC);

CREATE INDEX IF NOT EXISTS idx_quiz_questions_active_category ON public.quiz_questions USING btree (is_active, category, difficulty);

CREATE UNIQUE INDEX IF NOT EXISTS quiz_questions_pkey ON public.quiz_questions USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS quiz_questions_question_code_key ON public.quiz_questions USING btree (question_code);

CREATE INDEX IF NOT EXISTS idx_tenant_fan_qr_invite_claims_tenant ON public.tenant_fan_qr_invite_claims USING btree (tenant_slug, claimed_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_fan_qr_invite_claims_invite_id_user_id_key ON public.tenant_fan_qr_invite_claims USING btree (invite_id, user_id);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_fan_qr_invite_claims_pkey ON public.tenant_fan_qr_invite_claims USING btree (id);

CREATE INDEX IF NOT EXISTS idx_tenant_fan_qr_invites_registration_type ON public.tenant_fan_qr_invites USING btree (tenant_slug, registration_type, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_tenant_fan_qr_invites_tenant_status ON public.tenant_fan_qr_invites USING btree (tenant_slug, status, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_fan_qr_invites_invite_token_key ON public.tenant_fan_qr_invites USING btree (invite_token);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_fan_qr_invites_pkey ON public.tenant_fan_qr_invites USING btree (id);

CREATE INDEX IF NOT EXISTS idx_tenant_insight_drafts_updated ON public.tenant_insight_drafts USING btree (tenant_slug, updated_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_insight_drafts_pkey ON public.tenant_insight_drafts USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_insight_drafts_tenant_slug_draft_id_key ON public.tenant_insight_drafts USING btree (tenant_slug, draft_id);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_registry_pkey ON public.tenant_registry USING btree (tenant_slug);

CREATE INDEX IF NOT EXISTS idx_tenant_subscription_products_active ON public.tenant_subscription_products USING btree (tenant_slug, status, updated_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_subscription_products_pkey ON public.tenant_subscription_products USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_subscription_products_tenant_slug_product_code_key ON public.tenant_subscription_products USING btree (tenant_slug, product_code);

CREATE INDEX IF NOT EXISTS idx_user_quiz_answers_attempt ON public.user_quiz_answers USING btree (attempt_id);

CREATE UNIQUE INDEX IF NOT EXISTS user_quiz_answers_attempt_id_question_id_key ON public.user_quiz_answers USING btree (attempt_id, question_id);

CREATE UNIQUE INDEX IF NOT EXISTS user_quiz_answers_pkey ON public.user_quiz_answers USING btree (id);

CREATE INDEX IF NOT EXISTS idx_user_quiz_attempts_tenant_date ON public.user_quiz_attempts USING btree (tenant_slug, quiz_date, completed_at);

CREATE UNIQUE INDEX IF NOT EXISTS uq_user_quiz_attempts_user_date_no ON public.user_quiz_attempts USING btree (user_id, quiz_date, attempt_no);

CREATE UNIQUE INDEX IF NOT EXISTS user_quiz_attempts_pkey ON public.user_quiz_attempts USING btree (id);

CREATE INDEX IF NOT EXISTS idx_fan_stock_observation_user_id ON public.fan_stock_observation_events USING btree (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_user_watchlist_items_user_id ON public.user_watchlist_items USING btree (user_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_watchlist_comments_created_by_user_pk ON public.watchlist_comments USING btree (created_by_user_pk, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_watchlist_annotations_created_by_user_pk ON public.watchlist_kline_annotations USING btree (created_by_user_pk, updated_at DESC);
