-- Generated by the local-to-target delta scanner.
-- Additive only: target-only rows and destructive schema changes are excluded.

CREATE TABLE IF NOT EXISTS "fan_payment_orders" (
    "id" bigint DEFAULT nextval('fan_payment_orders_id_seq'::regclass) NOT NULL,
    "order_no" text NOT NULL,
    "tenant_slug" text NOT NULL,
    "user_id" bigint NOT NULL,
    "product_id" bigint NOT NULL,
    "amount_cents" integer NOT NULL,
    "currency" text DEFAULT 'CNY'::text NOT NULL,
    "payment_channel" text DEFAULT 'manual_transfer'::text NOT NULL,
    "status" text DEFAULT 'pending'::text NOT NULL,
    "provider_trade_no" text DEFAULT ''::text NOT NULL,
    "payment_reference" text DEFAULT ''::text NOT NULL,
    "metadata_json" text DEFAULT '{}'::text NOT NULL,
    "created_at" text NOT NULL,
    "expires_at" text NOT NULL,
    "paid_at" text DEFAULT ''::text NOT NULL,
    "confirmed_by_user_id" bigint,
    "confirmed_at" text DEFAULT ''::text NOT NULL,
    "updated_at" text NOT NULL
);

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fan_payment_orders_amount_cents_check') THEN ALTER TABLE "fan_payment_orders" ADD CONSTRAINT "fan_payment_orders_amount_cents_check" CHECK (amount_cents >= 0); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fan_payment_orders_order_no_key') THEN ALTER TABLE "fan_payment_orders" ADD CONSTRAINT "fan_payment_orders_order_no_key" UNIQUE (order_no); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fan_payment_orders_pkey') THEN ALTER TABLE "fan_payment_orders" ADD CONSTRAINT "fan_payment_orders_pkey" PRIMARY KEY (id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fan_payment_orders_product_id_fkey') THEN ALTER TABLE "fan_payment_orders" ADD CONSTRAINT "fan_payment_orders_product_id_fkey" FOREIGN KEY (product_id) REFERENCES tenant_subscription_products(id) ON DELETE RESTRICT; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fan_payment_orders_status_check') THEN ALTER TABLE "fan_payment_orders" ADD CONSTRAINT "fan_payment_orders_status_check" CHECK (status = ANY (ARRAY['pending'::text, 'paid'::text, 'cancelled'::text, 'expired'::text, 'refunded'::text])); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fan_payment_orders_user_id_fkey') THEN ALTER TABLE "fan_payment_orders" ADD CONSTRAINT "fan_payment_orders_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT; END IF; END $$;

CREATE UNIQUE INDEX IF NOT EXISTS fan_payment_orders_order_no_key ON public.fan_payment_orders USING btree (order_no);

CREATE UNIQUE INDEX IF NOT EXISTS fan_payment_orders_pkey ON public.fan_payment_orders USING btree (id);

CREATE INDEX IF NOT EXISTS idx_fan_payment_orders_tenant_status ON public.fan_payment_orders USING btree (tenant_slug, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_fan_payment_orders_user_status ON public.fan_payment_orders USING btree (user_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS "fan_subscriptions" (
    "id" bigint DEFAULT nextval('fan_subscriptions_id_seq'::regclass) NOT NULL,
    "tenant_slug" text NOT NULL,
    "user_id" bigint NOT NULL,
    "product_id" bigint NOT NULL,
    "order_id" bigint NOT NULL,
    "status" text DEFAULT 'active'::text NOT NULL,
    "starts_at" text NOT NULL,
    "expires_at" text NOT NULL,
    "created_at" text NOT NULL,
    "updated_at" text NOT NULL
);

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fan_subscriptions_order_id_fkey') THEN ALTER TABLE "fan_subscriptions" ADD CONSTRAINT "fan_subscriptions_order_id_fkey" FOREIGN KEY (order_id) REFERENCES fan_payment_orders(id) ON DELETE RESTRICT; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fan_subscriptions_order_id_key') THEN ALTER TABLE "fan_subscriptions" ADD CONSTRAINT "fan_subscriptions_order_id_key" UNIQUE (order_id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fan_subscriptions_pkey') THEN ALTER TABLE "fan_subscriptions" ADD CONSTRAINT "fan_subscriptions_pkey" PRIMARY KEY (id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fan_subscriptions_product_id_fkey') THEN ALTER TABLE "fan_subscriptions" ADD CONSTRAINT "fan_subscriptions_product_id_fkey" FOREIGN KEY (product_id) REFERENCES tenant_subscription_products(id) ON DELETE RESTRICT; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fan_subscriptions_status_check') THEN ALTER TABLE "fan_subscriptions" ADD CONSTRAINT "fan_subscriptions_status_check" CHECK (status = ANY (ARRAY['active'::text, 'expired'::text, 'cancelled'::text, 'refunded'::text])); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fan_subscriptions_user_id_fkey') THEN ALTER TABLE "fan_subscriptions" ADD CONSTRAINT "fan_subscriptions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT; END IF; END $$;

CREATE UNIQUE INDEX IF NOT EXISTS fan_subscriptions_order_id_key ON public.fan_subscriptions USING btree (order_id);

CREATE UNIQUE INDEX IF NOT EXISTS fan_subscriptions_pkey ON public.fan_subscriptions USING btree (id);

CREATE INDEX IF NOT EXISTS idx_fan_subscriptions_access ON public.fan_subscriptions USING btree (tenant_slug, user_id, status, expires_at DESC);

CREATE TABLE IF NOT EXISTS "tenant_fan_qr_invite_claims" (
    "id" bigint DEFAULT nextval('tenant_fan_qr_invite_claims_id_seq'::regclass) NOT NULL,
    "invite_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "tenant_slug" text NOT NULL,
    "claimed_at" text NOT NULL
);

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_fan_qr_invite_claims_invite_id_fkey') THEN ALTER TABLE "tenant_fan_qr_invite_claims" ADD CONSTRAINT "tenant_fan_qr_invite_claims_invite_id_fkey" FOREIGN KEY (invite_id) REFERENCES tenant_fan_qr_invites(id) ON DELETE CASCADE; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_fan_qr_invite_claims_invite_id_user_id_key') THEN ALTER TABLE "tenant_fan_qr_invite_claims" ADD CONSTRAINT "tenant_fan_qr_invite_claims_invite_id_user_id_key" UNIQUE (invite_id, user_id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_fan_qr_invite_claims_pkey') THEN ALTER TABLE "tenant_fan_qr_invite_claims" ADD CONSTRAINT "tenant_fan_qr_invite_claims_pkey" PRIMARY KEY (id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_fan_qr_invite_claims_user_id_fkey') THEN ALTER TABLE "tenant_fan_qr_invite_claims" ADD CONSTRAINT "tenant_fan_qr_invite_claims_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT; END IF; END $$;

CREATE INDEX IF NOT EXISTS idx_tenant_fan_qr_invite_claims_tenant ON public.tenant_fan_qr_invite_claims USING btree (tenant_slug, claimed_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_fan_qr_invite_claims_invite_id_user_id_key ON public.tenant_fan_qr_invite_claims USING btree (invite_id, user_id);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_fan_qr_invite_claims_pkey ON public.tenant_fan_qr_invite_claims USING btree (id);

CREATE TABLE IF NOT EXISTS "tenant_fan_qr_invites" (
    "id" bigint DEFAULT nextval('tenant_fan_qr_invites_id_seq'::regclass) NOT NULL,
    "invite_token" text NOT NULL,
    "tenant_slug" text NOT NULL,
    "source_label" text DEFAULT '扫码导入'::text NOT NULL,
    "note" text DEFAULT ''::text NOT NULL,
    "status" text DEFAULT 'active'::text NOT NULL,
    "max_uses" integer DEFAULT 0 NOT NULL,
    "used_count" integer DEFAULT 0 NOT NULL,
    "expires_at" text DEFAULT ''::text NOT NULL,
    "created_by_user_id" bigint,
    "created_at" text NOT NULL,
    "updated_at" text NOT NULL
);

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_fan_qr_invites_invite_token_key') THEN ALTER TABLE "tenant_fan_qr_invites" ADD CONSTRAINT "tenant_fan_qr_invites_invite_token_key" UNIQUE (invite_token); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_fan_qr_invites_max_uses_check') THEN ALTER TABLE "tenant_fan_qr_invites" ADD CONSTRAINT "tenant_fan_qr_invites_max_uses_check" CHECK (max_uses >= 0); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_fan_qr_invites_pkey') THEN ALTER TABLE "tenant_fan_qr_invites" ADD CONSTRAINT "tenant_fan_qr_invites_pkey" PRIMARY KEY (id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_fan_qr_invites_status_check') THEN ALTER TABLE "tenant_fan_qr_invites" ADD CONSTRAINT "tenant_fan_qr_invites_status_check" CHECK (status = ANY (ARRAY['active'::text, 'disabled'::text, 'expired'::text])); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_fan_qr_invites_used_count_check') THEN ALTER TABLE "tenant_fan_qr_invites" ADD CONSTRAINT "tenant_fan_qr_invites_used_count_check" CHECK (used_count >= 0); END IF; END $$;

CREATE INDEX IF NOT EXISTS idx_tenant_fan_qr_invites_tenant_status ON public.tenant_fan_qr_invites USING btree (tenant_slug, status, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_fan_qr_invites_invite_token_key ON public.tenant_fan_qr_invites USING btree (invite_token);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_fan_qr_invites_pkey ON public.tenant_fan_qr_invites USING btree (id);

CREATE TABLE IF NOT EXISTS "tenant_insight_drafts" (
    "id" bigint DEFAULT nextval('tenant_insight_drafts_id_seq'::regclass) NOT NULL,
    "tenant_slug" text NOT NULL,
    "draft_id" text NOT NULL,
    "title" text DEFAULT ''::text NOT NULL,
    "content_text" text NOT NULL,
    "source_mode" text DEFAULT 'manual'::text NOT NULL,
    "access_mode" text DEFAULT 'public'::text NOT NULL,
    "created_at" text NOT NULL,
    "updated_at" text NOT NULL
);

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_insight_drafts_pkey') THEN ALTER TABLE "tenant_insight_drafts" ADD CONSTRAINT "tenant_insight_drafts_pkey" PRIMARY KEY (id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_insight_drafts_tenant_slug_draft_id_key') THEN ALTER TABLE "tenant_insight_drafts" ADD CONSTRAINT "tenant_insight_drafts_tenant_slug_draft_id_key" UNIQUE (tenant_slug, draft_id); END IF; END $$;

CREATE INDEX IF NOT EXISTS idx_tenant_insight_drafts_updated ON public.tenant_insight_drafts USING btree (tenant_slug, updated_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_insight_drafts_pkey ON public.tenant_insight_drafts USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_insight_drafts_tenant_slug_draft_id_key ON public.tenant_insight_drafts USING btree (tenant_slug, draft_id);

CREATE TABLE IF NOT EXISTS "tenant_registry" (
    "tenant_slug" text NOT NULL,
    "tenant_name" text DEFAULT ''::text NOT NULL,
    "created_at" text NOT NULL,
    "updated_at" text NOT NULL
);

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_registry_pkey') THEN ALTER TABLE "tenant_registry" ADD CONSTRAINT "tenant_registry_pkey" PRIMARY KEY (tenant_slug); END IF; END $$;

CREATE UNIQUE INDEX IF NOT EXISTS tenant_registry_pkey ON public.tenant_registry USING btree (tenant_slug);

CREATE TABLE IF NOT EXISTS "tenant_subscription_products" (
    "id" bigint DEFAULT nextval('tenant_subscription_products_id_seq'::regclass) NOT NULL,
    "tenant_slug" text NOT NULL,
    "product_code" text NOT NULL,
    "name" text NOT NULL,
    "description" text DEFAULT ''::text NOT NULL,
    "price_cents" integer NOT NULL,
    "billing_period_days" integer NOT NULL,
    "status" text DEFAULT 'active'::text NOT NULL,
    "created_by_user_id" bigint,
    "created_at" text NOT NULL,
    "updated_at" text NOT NULL
);

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_subscription_products_billing_period_days_check') THEN ALTER TABLE "tenant_subscription_products" ADD CONSTRAINT "tenant_subscription_products_billing_period_days_check" CHECK (billing_period_days > 0); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_subscription_products_pkey') THEN ALTER TABLE "tenant_subscription_products" ADD CONSTRAINT "tenant_subscription_products_pkey" PRIMARY KEY (id); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_subscription_products_price_cents_check') THEN ALTER TABLE "tenant_subscription_products" ADD CONSTRAINT "tenant_subscription_products_price_cents_check" CHECK (price_cents >= 0); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_subscription_products_status_check') THEN ALTER TABLE "tenant_subscription_products" ADD CONSTRAINT "tenant_subscription_products_status_check" CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'archived'::text])); END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_subscription_products_tenant_slug_product_code_key') THEN ALTER TABLE "tenant_subscription_products" ADD CONSTRAINT "tenant_subscription_products_tenant_slug_product_code_key" UNIQUE (tenant_slug, product_code); END IF; END $$;

CREATE INDEX IF NOT EXISTS idx_tenant_subscription_products_active ON public.tenant_subscription_products USING btree (tenant_slug, status, updated_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_subscription_products_pkey ON public.tenant_subscription_products USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_subscription_products_tenant_slug_product_code_key ON public.tenant_subscription_products USING btree (tenant_slug, product_code);

ALTER TABLE "fan_stock_observation_events" ADD COLUMN IF NOT EXISTS "user_id" bigint;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_fan_stock_observation_user') THEN ALTER TABLE "fan_stock_observation_events" ADD CONSTRAINT "fk_fan_stock_observation_user" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL; END IF; END $$;

CREATE INDEX IF NOT EXISTS idx_fan_stock_observation_user_id ON public.fan_stock_observation_events USING btree (user_id, created_at DESC);

ALTER TABLE "user_watchlist_items" ADD COLUMN IF NOT EXISTS "user_id" bigint;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_watchlist_items_user') THEN ALTER TABLE "user_watchlist_items" ADD CONSTRAINT "fk_user_watchlist_items_user" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL; END IF; END $$;

CREATE INDEX IF NOT EXISTS idx_user_watchlist_items_user_id ON public.user_watchlist_items USING btree (user_id, updated_at DESC);

ALTER TABLE "watchlist_comments" ADD COLUMN IF NOT EXISTS "created_by_user_pk" bigint;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_watchlist_comments_created_by_user') THEN ALTER TABLE "watchlist_comments" ADD CONSTRAINT "fk_watchlist_comments_created_by_user" FOREIGN KEY (created_by_user_pk) REFERENCES users(id) ON DELETE SET NULL; END IF; END $$;

CREATE INDEX IF NOT EXISTS idx_watchlist_comments_created_by_user_pk ON public.watchlist_comments USING btree (created_by_user_pk, updated_at DESC);

ALTER TABLE "watchlist_kline_annotations" ADD COLUMN IF NOT EXISTS "created_by_user_pk" bigint;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_watchlist_annotations_created_by_user') THEN ALTER TABLE "watchlist_kline_annotations" ADD CONSTRAINT "fk_watchlist_annotations_created_by_user" FOREIGN KEY (created_by_user_pk) REFERENCES users(id) ON DELETE SET NULL; END IF; END $$;

CREATE INDEX IF NOT EXISTS idx_watchlist_annotations_created_by_user_pk ON public.watchlist_kline_annotations USING btree (created_by_user_pk, updated_at DESC);
